/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AmateurScuba;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Paint;
import java.text.DecimalFormat;
import javafx.scene.chart.CategoryAxis;
import javafx.scene.chart.ValueAxis;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.labels.ItemLabelAnchor;
import org.jfree.chart.labels.ItemLabelPosition;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.GroupedStackedBarRenderer;
import org.jfree.chart.title.DateTitle;
import org.jfree.data.KeyToGroupMap;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.GradientPaintTransformType;
import org.jfree.ui.RefineryUtilities;
import org.jfree.ui.StandardGradientPaintTransformer;
import org.jfree.ui.TextAnchor;

/**
 *
 * @author Louis
 */
public class Calculations extends javax.swing.JFrame {
//1 for MOD /2 for Best Mix /3 for  PP / 4 forEAD /5 for SMOD
private int flag =1;

    public int getFlag() {
        return flag;
    }

    public void setFlag(int flag) {
        this.flag = flag;
    }

   
 

    /**
     * Creates new form Calculations
     */
    public Calculations() {
        initComponents();
        this.tableJLabel.setText("EAD Table (Oxygen(%)/Depth(m))");
               JTable jt =  MethodsContainer.eadTable();
       
       this.tableJScrollPane.setViewportView(jt);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseJPanel = new javax.swing.JPanel();
        menuJPanel = new javax.swing.JPanel();
        calculationJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        calculateJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        cylinderJPanel = new javax.swing.JPanel();
        tableJPanel = new javax.swing.JPanel();
        tableJScrollPane = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tableLabelJPanel = new javax.swing.JPanel();
        tableJLabel = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        calculationJMenu = new javax.swing.JMenu();
        modJMenuItem = new javax.swing.JMenuItem();
        bmJMenuItem = new javax.swing.JMenuItem();
        ppJMenuItem = new javax.swing.JMenuItem();
        eadJMenuItem = new javax.swing.JMenuItem();
        smodJMenuItem = new javax.swing.JMenuItem();
        tableJMenu = new javax.swing.JMenu();
        eadTableJMenuItem = new javax.swing.JMenuItem();
        ppTableJMenuItem = new javax.swing.JMenuItem();
        helpJMenu = new javax.swing.JMenu();
        aboutJMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        baseJPanel.setBackground(new java.awt.Color(255, 0, 102));

        menuJPanel.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout menuJPanelLayout = new javax.swing.GroupLayout(menuJPanel);
        menuJPanel.setLayout(menuJPanelLayout);
        menuJPanelLayout.setHorizontalGroup(
            menuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        menuJPanelLayout.setVerticalGroup(
            menuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        calculationJPanel.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Fg");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pg");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        calculateJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculateJButton.setText("Calculate MOD");
        calculateJButton.setToolTipText("");
        calculateJButton.setActionCommand("calculateJButton");
        calculateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateJButtonActionPerformed(evt);
            }
        });

        jTextPane1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout calculationJPanelLayout = new javax.swing.GroupLayout(calculationJPanel);
        calculationJPanel.setLayout(calculationJPanelLayout);
        calculationJPanelLayout.setHorizontalGroup(
            calculationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculationJPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(calculationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calculationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(calculateJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(calculationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        calculationJPanelLayout.setVerticalGroup(
            calculationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculationJPanelLayout.createSequentialGroup()
                .addGroup(calculationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calculationJPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calculationJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(calculationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(calculationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calculationJPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(calculateJButton))
                    .addGroup(calculationJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        cylinderJPanel.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout cylinderJPanelLayout = new javax.swing.GroupLayout(cylinderJPanel);
        cylinderJPanel.setLayout(cylinderJPanelLayout);
        cylinderJPanelLayout.setHorizontalGroup(
            cylinderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cylinderJPanelLayout.setVerticalGroup(
            cylinderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout baseJPanelLayout = new javax.swing.GroupLayout(baseJPanel);
        baseJPanel.setLayout(baseJPanelLayout);
        baseJPanelLayout.setHorizontalGroup(
            baseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseJPanelLayout.createSequentialGroup()
                .addGroup(baseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseJPanelLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(menuJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(calculationJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cylinderJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        baseJPanelLayout.setVerticalGroup(
            baseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseJPanelLayout.createSequentialGroup()
                .addComponent(calculationJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cylinderJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableJPanel.setBackground(new java.awt.Color(255, 0, 255));

        tableJScrollPane.setBackground(new java.awt.Color(153, 255, 51));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(51, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jTable1.setRowSorter(null);
        tableJScrollPane.setViewportView(jTable1);

        javax.swing.GroupLayout tableJPanelLayout = new javax.swing.GroupLayout(tableJPanel);
        tableJPanel.setLayout(tableJPanelLayout);
        tableJPanelLayout.setHorizontalGroup(
            tableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableJScrollPane)
                .addContainerGap())
        );
        tableJPanelLayout.setVerticalGroup(
            tableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableJScrollPane)
                .addContainerGap())
        );

        tableJLabel.setBackground(new java.awt.Color(0, 255, 51));
        tableJLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        tableJLabel.setForeground(new java.awt.Color(0, 0, 153));
        tableJLabel.setText("Table");

        javax.swing.GroupLayout tableLabelJPanelLayout = new javax.swing.GroupLayout(tableLabelJPanel);
        tableLabelJPanel.setLayout(tableLabelJPanelLayout);
        tableLabelJPanelLayout.setHorizontalGroup(
            tableLabelJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableLabelJPanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(tableJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        tableLabelJPanelLayout.setVerticalGroup(
            tableLabelJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableLabelJPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tableJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar.setBackground(new java.awt.Color(255, 204, 255));

        calculationJMenu.setText("Calculations");
        calculationJMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        modJMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        modJMenuItem.setText("MOD");
        modJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modJMenuItemActionPerformed(evt);
            }
        });
        calculationJMenu.add(modJMenuItem);

        bmJMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bmJMenuItem.setText("BM");
        bmJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmJMenuItemActionPerformed(evt);
            }
        });
        calculationJMenu.add(bmJMenuItem);

        ppJMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ppJMenuItem.setText("PP");
        ppJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppJMenuItemActionPerformed(evt);
            }
        });
        calculationJMenu.add(ppJMenuItem);

        eadJMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eadJMenuItem.setText("EAD");
        eadJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eadJMenuItemActionPerformed(evt);
            }
        });
        calculationJMenu.add(eadJMenuItem);

        smodJMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        smodJMenuItem.setText("SMOD");
        smodJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smodJMenuItemActionPerformed(evt);
            }
        });
        calculationJMenu.add(smodJMenuItem);

        jMenuBar.add(calculationJMenu);

        tableJMenu.setText("Tables");
        tableJMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        eadTableJMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eadTableJMenuItem.setText("EAD");
        eadTableJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eadTableJMenuItemActionPerformed(evt);
            }
        });
        tableJMenu.add(eadTableJMenuItem);

        ppTableJMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ppTableJMenuItem.setText("PP");
        ppTableJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppTableJMenuItemActionPerformed(evt);
            }
        });
        tableJMenu.add(ppTableJMenuItem);

        jMenuBar.add(tableJMenu);

        helpJMenu.setText("Help");
        helpJMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar.add(helpJMenu);

        aboutJMenu.setText("About");
        aboutJMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar.add(aboutJMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(baseJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableLabelJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baseJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tableLabelJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tableJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modJMenuItemActionPerformed
        // TODO add your handling code here:
        flag = 1;
        this.jLabel1.setText("Pg");
        this.jLabel2.setText("Fg");
        this.jTextField1.setEditable(true);
        this.calculateJButton.setText("Calculate MOD");
        
    }//GEN-LAST:event_modJMenuItemActionPerformed

    private void bmJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmJMenuItemActionPerformed
        // TODO add your handling code here:
        flag = 2;
        this.jLabel1.setText("Pg");
        this.jLabel2.setText("Depth");
    this.jTextField1.setEditable(true);
        this.calculateJButton.setText("Calculate BM");
        
    }//GEN-LAST:event_bmJMenuItemActionPerformed

    private void ppJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppJMenuItemActionPerformed
        // TODO add your handling code here:
        flag = 3;
        this.jLabel1.setText("Fg");
        this.jLabel2.setText("Depth");
 this.jTextField1.setEditable(true);
        this.calculateJButton.setText("Calculate PP");
        
    }//GEN-LAST:event_ppJMenuItemActionPerformed

    private void eadJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eadJMenuItemActionPerformed
        // TODO add your handling code here:
        flag = 4;
        this.jLabel1.setText("Fg");
        this.jLabel2.setText("Depth");
  this.jTextField1.setEditable(true);
        this.calculateJButton.setText("Calculate EAD");
    }//GEN-LAST:event_eadJMenuItemActionPerformed

    private void smodJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smodJMenuItemActionPerformed
        // TODO add your handling code here:
        flag = 5;
        this.jLabel1.setText("Pg");
        this.jLabel2.setText("Fg");
        this.jTextField1.setText("1.4");
        
   this.jTextField1.setEditable(false);
        this.calculateJButton.setText("Calculate SMOD");
    }//GEN-LAST:event_smodJMenuItemActionPerformed

    private void calculateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateJButtonActionPerformed
        // TODO add your handling code here:
        double result = MethodsContainer.calculator(this.flag, this.jTextField1.getText(),this.jTextField2.getText());
                
                
        DecimalFormat df = new DecimalFormat("0.00");
        String output;
        switch (flag) {
            case 1:
                
            output = "MOD Value is "+df.format(result)+"m";
                break;
            case 2:
                
            output = "BM Value is "+df.format(result);
                break;
            case 3:
                    
            output = "PP Value is "+df.format(result)+"ata";
                break;
            case 4:
                    
            output = "EAD Value is "+df.format(result)+"m";
                break;
            case 5:
                         
            output = "SMOD Value is "+df.format(result)+"m";       
                break;
            default:
                output=""; 
        }
        this.jTextPane1.setText(output);
        double oxygen = MethodsContainer.calculateOxygen(this.flag, this.jTextField1.getText(),this.jTextField2.getText());
        ChartPanel chartPanel= MethodsContainer.cylinderBuilder(oxygen);
this.cylinderJPanel.setLayout(new java.awt.BorderLayout());
this.cylinderJPanel.add(chartPanel);
this.cylinderJPanel.validate(); 
        
    }//GEN-LAST:event_calculateJButtonActionPerformed

    private void eadTableJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eadTableJMenuItemActionPerformed
        // TODO add your handling code here:
        JTable jt =  MethodsContainer.eadTable();
       this.tableJLabel.setText("EAD Table (Oxygen(%)/Depth(m))");
       this.tableJScrollPane.setViewportView(jt);


    }//GEN-LAST:event_eadTableJMenuItemActionPerformed

    private void ppTableJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppTableJMenuItemActionPerformed
        // TODO add your handling code here:
      
       JTable jt =  MethodsContainer.ppTable();
       this.tableJLabel.setText("PP Table (Oxygen(%)/Depth(m))");
       this.tableJScrollPane.setViewportView(jt);
    }//GEN-LAST:event_ppTableJMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
             Calculations c=   new Calculations();

             c.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutJMenu;
    private javax.swing.JPanel baseJPanel;
    private javax.swing.JMenuItem bmJMenuItem;
    private javax.swing.JButton calculateJButton;
    private javax.swing.JMenu calculationJMenu;
    private javax.swing.JPanel calculationJPanel;
    private javax.swing.JPanel cylinderJPanel;
    private javax.swing.JMenuItem eadJMenuItem;
    private javax.swing.JMenuItem eadTableJMenuItem;
    private javax.swing.JMenu helpJMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel menuJPanel;
    private javax.swing.JMenuItem modJMenuItem;
    private javax.swing.JMenuItem ppJMenuItem;
    private javax.swing.JMenuItem ppTableJMenuItem;
    private javax.swing.JMenuItem smodJMenuItem;
    private javax.swing.JLabel tableJLabel;
    private javax.swing.JMenu tableJMenu;
    private javax.swing.JPanel tableJPanel;
    private javax.swing.JScrollPane tableJScrollPane;
    private javax.swing.JPanel tableLabelJPanel;
    // End of variables declaration//GEN-END:variables
}
